<?php
declare(strict_types=1);
if (!defined('MTX_FRONT_CONTROLLER')) { http_response_code(404); exit; }
use MTX\{Http,Security,Releases,GameIds};
$app=require dirname(__DIR__,2).'/src/bootstrap.php';
Http::method('GET'); Security::session($app);
if (!Security::loggedIn($app)) Http::redirect($app->path('/admin/login.php'));
header('Cache-Control: no-store');
$s=$app->store->read();
GameIds::rejectLegacyFields($_GET);
$g=GameIds::resolve($s,$_GET+['game_id'=>1]);
$gameID=$g['game_id'];
$key=$g['app_key'];
$releases=array_reverse(array_values(array_filter($s['releases'],fn($r)=>$r['app_key']===$key)));
$current=$g['current_release_id']?Releases::release($s,$g['current_release_id']):null;
$url=$app->url('/api/update.php');
$flash=$_SESSION['flash']??''; unset($_SESSION['flash']);
function e(mixed $v): string { return Http::escape($v); }
function fields(string $action,?int $gameID=null,array $extra=[]): void {
    $values=['csrf'=>$_SESSION['csrf'],'action'=>$action]+$extra;
    if ($gameID!==null) $values['game_id']=$gameID;
    foreach ($values as $name=>$value) echo '<input type="hidden" name="'.e($name).'" value="'.e($value).'">';
}
function dateLabel(string $value): string { return (new DateTimeImmutable($value))->setTimezone(new DateTimeZone('Asia/Shanghai'))->format('Y-m-d H:i'); }
function sizeLabel(?int $size): string { return $size===null?'—':number_format($size/1048576,2).' MiB'; }
$labels=['draft'=>'等待自动处理','ready'=>'待发布','published'=>'已发布','withdrawn'=>'已下架'];
?>
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($g['name'])?> · 满天星更新中心</title><link rel="stylesheet" href="<?=MTX\Http::escape($app->path('/assets/app.css'))?>?v=admin2"><script src="<?=MTX\Http::escape($app->path('/assets/app.js'))?>?v=admin2" defer></script><?php MTX\AdminLayout::assets($app); ?></head><body>
<?php MTX\AdminLayout::begin($app,'游戏更新','releases'); ?><main class="content"><section class="game-switcher panel"><label for="game-switch">当前游戏</label><select id="game-switch" data-game-switch><?php foreach ($s['apps'] as $game): ?><option value="<?=e($app->path('/admin/').'?game_id='.$game['game_id'])?>" <?=$game['game_id']===$gameID?'selected':''?>><?=e($game['name'])?> · ID <?=e($game['game_id'])?></option><?php endforeach ?></select><button type="button" class="button quiet" data-dialog="game-dialog">＋ 新增游戏</button></section><div class="page-heading"><div><div class="eyebrow">RELEASE WORKSPACE</div><h1><?=e($g['name'])?></h1><p class="muted">管理这个游戏的更新包。所有游戏共用同一个接口，通过游戏 ID 区分。</p></div><a class="button primary" href="#upload">↑ 上传新版本</a></div>
<?php if ($flash): ?><div class="notice success" role="status"><?=e($flash)?></div><?php endif ?>
<details class="endpoint advanced-endpoint"><summary>更新接口与游戏 ID</summary><div class="endpoint-content"><div><span class="endpoint-label">共用更新接口 · 游戏 ID <?=e($g['game_id'])?></span><code><?=e($url)?></code></div><button class="button quiet" type="button" data-copy="<?=e($url)?>">复制地址</button></div></details>
<div class="metrics"><section class="metric"><span>当前线上版本</span><strong><?=$current?e($current['display_version']):'尚未发布'?></strong><small><?=$current?'发布序号 #'.e($current['sequence']):'上传并发布后开始分发'?></small></section><section class="metric"><span>分发包大小</span><strong><?=sizeLabel($current['artifact_bytes']??null)?></strong><small><?=$g['format']==='tipa'?'原始 TIPA':'由服务器自动准备安装资源'?></small></section><section class="metric"><span>更新接口</span><strong class="status-text"><span class="dot <?=$g['enabled']?'':'off'?>"></span><?=$g['enabled']?'已启用':'已停用'?></strong><small><?=count($releases)?> 条版本记录 · 配置 v<?=e($g['revision'])?></small></section></div>
<div class="work-grid"><section class="panel upload-panel" id="upload"><div class="section-title"><div><span class="step-number">01</span><h2>上传新版本</h2></div><span class="subtle-tag">TIPA</span></div><p class="muted compact">只需上传与此游戏安装器匹配的辅助 TIPA。其余资源由服务器自动处理，无需补传。</p><form method="post" action="<?=MTX\Http::escape($app->path('/admin/action.php'))?>" enctype="multipart/form-data" class="upload-form"><?php fields('upload',$gameID) ?><label class="drop-zone" for="tipa-file"><span class="upload-symbol">↑</span><strong>选择 TIPA 更新包</strong><span>点击选择文件 · 最大 256 MiB</span><input id="tipa-file" type="file" name="file" accept=".tipa" required><span class="file-label" aria-live="polite">还未选择文件</span></label><label for="changelog">后台备注（可选）</label><textarea id="changelog" name="changelog" rows="3" maxlength="5000" placeholder="仅供后台管理查看，可留空。"></textarea><div class="upload-feedback" hidden><progress max="100" value="0"></progress><p role="status"></p></div><button class="button primary full" type="submit">上传并检查 <span>→</span></button></form></section>
<details class="panel binding-panel"><summary>安装器绑定与接口设置</summary><div class="section-title"><div><span class="step-number">02</span><h2>当前构建绑定</h2></div></div><p class="muted compact">这些值与对应安装器保持一致。</p><dl class="bindings"><dt>游戏 ID</dt><dd><?=e($g['game_id'])?></dd><dt>预期 Bundle ID</dt><dd><?=e($g['bundle_id'])?></dd><dt>产物契约</dt><dd><?=e($g['profile_id'])?></dd><dt>发布格式</dt><dd><?=e($g['format'])?></dd></dl><div class="note-box"><?php if ($g['format']==='prepared-payload-v1'): ?><strong>上传成功 ≠ 已发布</strong><p>只上传对应游戏的辅助 TIPA，服务器自动准备和校验安装资源。处理完成后确认发布，安装器按游戏 ID 下载。</p><?php else: ?><strong>原始 TIPA 分发</strong><p>此配置直接分发 TIPA，请使用与此游戏匹配的安装器。</p><?php endif ?></div><details class="public-config"><summary>查看安装器公钥配置</summary><pre><?=e(json_encode(['game_id'=>$g['game_id'],'update_url'=>$url,'expected_bundle_id'=>$g['bundle_id'],'profile_id'=>$g['profile_id'],'key_id'=>$app->config['key_id'],'public_key_base64'=>$app->config['sign_public'],'native_public_key_base64'=>$app->config['native_sign_public']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT))?></pre></details><form method="post" action="<?=MTX\Http::escape($app->path('/admin/action.php'))?>" data-confirm="确认切换这个游戏的更新接口状态？"><?php fields('toggle',$gameID,['revision'=>$g['revision']]) ?><button class="text-button" type="submit"><?=$g['enabled']?'停用此游戏接口':'启用此游戏接口'?></button></form></details></div>
<section class="versions"><div class="section-title"><div><span class="step-number">03</span><h2>版本记录</h2><span class="count"><?=count($releases)?></span></div><span class="muted">文件不可变 · 发布序号递增</span></div>
<?php if (!$releases): ?><div class="empty-state"><span class="empty-icon">↥</span><h3>准备好你的第一个版本</h3><p>上传 TIPA 后，版本号、包大小和检查状态会出现在这里。</p><a href="#upload" class="text-button">上传第一个更新包 →</a></div><?php endif ?>
<div id="release-table" aria-label="版本列表"></div><?php foreach ($releases as $r): $isCurrent=$g['current_release_id']===$r['release_id']; $prep=$r['preparation']??['status'=>'queued']; $prepLabel=['queued'=>'等待自动处理','processing'=>'正在自动处理','failed'=>'处理未完成'][$prep['status']]??'等待自动处理'; ?><article class="release-card" id="release-<?=e($r['release_id'])?>" data-release-id="<?=e($r['release_id'])?>"><details class="release-detail"><summary>版本 <?=e($r['display_version'])?> · <?=e($labels[$r['state']])?> · 查看详情与操作</summary><div class="release-header"><div class="version-identity"><span class="version-icon">↗</span><div><h3>版本 <?=e($r['display_version'])?> <span class="badge <?=e($r['state'])?>"><?=$isCurrent?'当前线上':e($r['state']==='draft'?$prepLabel:$labels[$r['state']])?></span></h3><p class="muted">Build <?=e($r['bundle_version'])?> <span>·</span> <?=e(dateLabel($r['created_at']))?></p></div></div><strong class="release-size"><?=sizeLabel($r['source_bytes'])?></strong></div><?php if (trim($r['changelog']??'')!==''): ?><p class="release-log"><strong>后台备注：</strong><?=nl2br(e($r['changelog']))?></p><?php endif ?><div class="release-meta"><span><?=$r['sequence']?'发布 #'.e($r['sequence']):'尚未分配发布序号'?></span></div><details class="hash-details"><summary>文件摘要与记录 ID</summary><p>源包 SHA-256 <code><?=e($r['source_sha256'])?></code></p><p>分发 SHA-256 <code><?=e($r['artifact_sha256']??'待准备')?></code></p><p>记录 ID <code><?=e($r['release_id'])?></code></p></details><div class="release-actions">
<?php if ($r['state']==='draft'): ?><div class="automatic-preparation"><strong><?=e($prepLabel)?></strong><p class="muted"><?=e(($prep['status']??'')==='failed'?($prep['error']??'自动处理未完成，请重试。'):'服务器会自动处理这份 TIPA，无需再上传其他文件。通常一分钟内开始，请稍后刷新。')?></p><a class="button quiet" href="<?=e($app->path('/admin/').'?game_id='.$gameID)?>">刷新处理状态</a><?php if (($prep['status']??'')==='failed'): ?><form method="post" action="<?=e($app->path('/admin/action.php'))?>"><?php fields('prepare_retry',$gameID,['release_id'=>$r['release_id']]) ?><button class="button" type="submit">重试自动处理</button></form><?php endif ?></div>
<?php elseif ($r['state']==='ready'): ?><form method="post" action="<?=MTX\Http::escape($app->path('/admin/action.php'))?>" class="publish-form" data-confirm="发布后，此游戏的固定接口会切换到这个版本。确认发布？"><?php fields('publish',$gameID,['release_id'=>$r['release_id'],'revision'=>$g['revision']]) ?><label class="checkbox"><input type="checkbox" name="confirmed" value="1" required>已完成对应安装器的兼容测试</label><button class="button primary" type="submit" <?=$g['enabled']?'':'disabled'?>>发布此版本 →</button></form>
<?php else: ?><form method="post" action="<?=MTX\Http::escape($app->path('/admin/action.php'))?>"><?php fields('republish',$gameID,['release_id'=>$r['release_id']]) ?><button class="button quiet" type="submit">复制为新发布草稿</button></form><?php endif ?>
<?php if ($r['state']!=='withdrawn'): ?><form method="post" action="<?=MTX\Http::escape($app->path('/admin/action.php'))?>" data-confirm="确认下架此版本？若为当前线上版本，接口将显示暂无发布。不会自动切回旧版。"><?php fields('withdraw',$gameID,['release_id'=>$r['release_id'],'revision'=>$g['revision']]) ?><button class="text-button danger" type="submit">下架</button></form><?php endif ?></div></details></article><?php endforeach ?></section>
<details class="panel audit"><summary>最近操作记录 <span class="muted">保留最近 1,000 条</span></summary><div class="audit-list"><?php foreach (array_slice(array_reverse($s['audit']),0,20) as $event): ?><div><time><?=e(dateLabel($event['time']))?></time><strong><?=e($event['action'])?></strong><span><?=e($event['target'])?></span></div><?php endforeach ?><?php if (!$s['audit']): ?><p class="muted">暂无操作记录。</p><?php endif ?></div></details><footer class="page-footer">MTX 更新中心 <span>只管理发布 · 安装行为由客户端确认执行</span></footer></main>
<dialog id="game-dialog"><form method="post" action="<?=MTX\Http::escape($app->path('/admin/action.php'))?>"><?php fields('create') ?><div class="dialog-heading"><h2>添加游戏配置</h2><button class="icon-button" type="button" data-close-dialog aria-label="关闭">×</button></div><p class="muted">游戏 ID 创建后自动生成；所有游戏使用同一接口，安装器配置对应 ID。</p><label>显示名称<input name="name" required maxlength="120" placeholder="满天星暗区突围国服"></label><label>实际 Bundle ID<input name="bundle_id" required maxlength="180" placeholder="以包内 Info.plist 为准"></label><input type="hidden" name="format" value="prepared-payload-v1"><p class="muted">上传辅助 TIPA 后自动处理，无需其他产物。</p><button class="button primary full" type="submit">创建游戏并分配 ID</button></form></dialog>
<div id="toast" role="status" hidden></div><?php MTX\AdminLayout::end(); ?></body></html>
